---
name: Tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
    branches:
    - master  
jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.6.6
          gemfile: Gemfile
        - ruby: 2.7.2
          gemfile: Gemfile
        - ruby: 3.0.1
          gemfile: Gemfile
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@master
    - name: Configure ChromeDriver and display server
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - name: Bundle
      run: |
        gem install bundler:2.2.15
        bundle install --no-deployment
    - name: Run tests
      uses: nick-invision/retry@v2
      with:
        timeout_seconds: 30
        max_attempts: 3
        command: bundle exec rake spec
